import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ar" dir="rtl">
            <body>
                <Sidebar>
                    <div className="bg-gray-100 min-h-screen">
                        <Header />
                        {children}
                    </div>
                </Sidebar>
            </body>
        </html>
    );
}
